# Generated by Django 5.1.2 on 2024-10-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='Número de Identificación'),
        ),
    ]
