# Generated by Django 5.0.4 on 2024-11-24 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_notification_promotion_reservationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='court_images/')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.court')),
            ],
            options={
                'verbose_name': 'Imagen de Cancha',
                'verbose_name_plural': 'Imagenes de Canchas',
            },
        ),
    ]
