# Generated by Django 5.0.4 on 2024-12-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_courtimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], default='tarjeta', max_length=20),
        ),
    ]
