# Generated by Django 5.0.4 on 2024-12-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Exitoso', 'Exitoso'), ('Pendiente', 'Pendiente'), ('Fallido', 'Fallido')], default='Exitoso', max_length=20),
        ),
    ]
